### PR TITLE
Change sudo usage methode

### PR DESCRIPTION
**Pull request by YoSiJo**
I had the problem that the script uses sudo.
For the commands zabbix but had no permission.
In order not to extend the rights too much, I limited the rights for Sudo to the script.
I would have liked to extend the license to the AGPL, but I leave that up to you and only ask you to do so.

### CODE REVIEW

**Comment by YoSiJo** [comment]
Sorry have a fail by sudoers file

**Comment by YoSiJo** [comment]
-.- Sorry local fail

**Comment by sergiotocalini** [comment]
The script is not intended to run globally with sudo privileges. Anyway, you are free to introduced your changes that you need on your our fork, I will take your advise and I will introduce some new features on the deploy script and I will provide the right documentation. Please feel free to check the repository in some time soon.

**Comment by YoSiJo** [comment]
I have create a branch for other implementation of sudoers solution: https://github.com/YoSiJo/zedisx/tree/dev0.1
When this way is better for you, then i create a new merge request.

**Pull request closed without merging**
